### ISSUE TITLE
Repeated CORS header accross the app

### ISSUE THREAD

**Issue by rafaelramalho19** [promatik/animaisderua#1]
**Friendly suggestion**

You should move this repeated logic to a Middleware, since that's their purpose :)

https://github.com/promatik/animaisderua/blob/a67f268a0b77b524f0970f1a770021a116c53b53/app/Http/Controllers/Admin/CrudController.php#L13-L14

**Comment by promatik** [comment]
Thank you for your suggestion @rafaelramalho19, it's fixed here: https://github.com/promatik/animaisderua/commit/217ddc2eacea135bcdaeff38d82d289fff598052.

The methods were removed since they were not being used.
When developing the API, if necessary, a method like this will go into a Middleware 👍
